if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'chriskempson/base16-vim'
Plug 'mboughaba/i3config.vim'
call plug#end()

set nocompatible
set term=xterm-256color
set t_Co=256
" hidden allows switching buffers without saving
set hidden
set number
set ruler
set nowrap
set autoindent
set shiftwidth=4
set softtabstop=4
set expandtab
set textwidth=120
set colorcolumn=+1
set laststatus=2

filetype plugin indent on
syntax on
syntax enable
let base16colorspace=256

nnoremap <Space> <Nop>
let mapleader = " "
nnoremap <Leader>i3 :set filetype=i3config<CR>

let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

nnoremap <C-p> :<C-u>FZF<CR>

colorscheme base16-default-dark
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif
