set nocompatible

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

filetype plugin indent on
syntax on

" hidden allows switching buffers without saving
set hidden
set number
set ruler
set nowrap
" set cindent
set autoindent
set shiftwidth=4
set softtabstop=4
set expandtab

set textwidth=120
set colorcolumn=+1

let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
" let &t_SR = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=2\x7\<Esc>\\"
" let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"

nnoremap <C-p> :<C-u>FZF<CR>

call plug#begin('~/.vim/plugged')

Plug 'pangloss/vim-javascript'
" Plug 'tbranyen/vim-typescript'
Plug 'leafgarland/typescript-vim'
Plug 'powerline/powerline'

call plug#end()

set rtp+=$HOME/Library/Python/2.7/lib/python/site-packages/powerline/bindings/vim
set laststatus=2

" Try out config

" Enable folding
set foldmethod=indent
set foldlevel=99
set omnifunc=syntaxcomplete#Complete

au FileType py
    \ set tabstop=4
    \ set softtabstop=4
    \ set shiftwidth=4
    \ set textwidth=79
    \ set expandtab
    \ set autoindent
    \ set fileformat=unix

autocmd Filetype python nnoremap <buffer> <F5> :w<CR>:term python3 "%"<CR>
