setxkbmap -layout gb
eval $(~/.fehbg &)
xrdb -merge ~/.Xresources
redshift-gtk &
exec dbus-launch i3
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
